folio-org/folio-s3-client

pom.xml
src/main/java/org/folio/s3/client/AwsS3Client.java
src/main/java/org/folio/s3/client/FolioS3Client.java
src/main/java/org/folio/s3/client/MinioS3Client.java
src/main/java/org/folio/s3/client/S3ClientFactory.java
src/main/java/org/folio/s3/client/S3ClientProperties.java
src/main/java/org/folio/s3/exception/S3ClientException.java
src/main/resources/log4j2.properties
src/test/java/org/folio/s3/client/FolioS3ClientTest.java
src/test/resources/log4j2.properties

[FOLS3CL-2](https://issues.folio.org/browse/FOLS3CL-2) - folio-s3-client implementation
folio-s3-client library implementation
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …

FOLS3CL-2 - folio-s3-client implementation

---

NEWS.md
pom.xml
src/main/resources/log4j2-json.properties

[FOLS3CL-6](https://issues.folio.org/browse/FOLS3CL-6) - folio-s3-client: module release

Release 1.0.0

---

README.md
pom.xml

[FOLS3CL-5](https://issues.folio.org/browse/FOLS3CL-5) - Make aws-sdk-java optional (maven scope: provided)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

FOLS3CL-5 - scope provided for aws-sdk-java

---

pom.xml
src/main/java/org/folio/s3/client/FolioS3Client.java
src/main/java/org/folio/s3/client/MinioS3Client.java
src/test/java/org/folio/s3/client/FolioS3ClientTest.java
src/test/resources/test-writer.json

Follow-up PR to [PR#8](https://github.com/folio-org/folio-s3-client/pull/8) with improvements/optimizations.

FOLS3CL-10 - folio-s3-client improvements

---

src/main/java/org/folio/s3/client/AwsS3Client.java
src/main/java/org/folio/s3/client/FolioS3Client.java
src/main/java/org/folio/s3/client/MinioS3Client.java
src/test/java/org/folio/s3/client/FolioS3ClientTest.java

Follow-up PR to [PR#8](https://github.com/folio-org/folio-s3-client/pull/8) with improvements/optimizations.

FOLS3CL-10 - folio-s3-client improvements (constructor refactoring)

---

pom.xml
src/main/java/org/folio/s3/client/AwsS3Client.java
src/main/java/org/folio/s3/client/MinioS3Client.java
src/test/java/org/folio/s3/client/FolioS3ClientTest.java

[FOLS3CL-18](https://issues.folio.org/browse/FOLS3CL-18) - OOM folio-s3-client writing (data-export)
Non-effective memory utilisation for large files writing.
Remove intermediate byte array for AWS S3 writing.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication …

FOLS3CL-18 - OOM folio-s3-client writing (data-export)

---

NEWS.md
pom.xml
src/main/java/org/folio/s3/client/AwsS3Client.java
src/main/java/org/folio/s3/client/MinioS3Client.java
src/test/java/org/folio/s3/client/FolioS3ClientTest.java

[FOLS3CL-19](https://issues.folio.org/browse/FOLS3CL-19) - Release 1.1.1

FOLS3CL-19 - Release 1.1.1

---

pom.xml

FOLS3CL-20 -  revert minio version

---

pom.xml

FOLS3CL-20 - revert minio version

---

pom.xml
src/main/java/org/folio/s3/client/MinioS3Client.java
src/test/java/org/folio/s3/client/FolioS3ClientTest.java

FOLS3CL-18 - folio-s3-client OOM during input stream writing

---

NEWS.md
pom.xml

This release contains reverting of AWS SDK version

FOLS3CL-19 - Release 2.0.1

---

NEWS.md
pom.xml
src/main/java/org/folio/s3/client/MinioS3Client.java
src/test/java/org/folio/s3/client/FolioS3ClientTest.java

[/FOLS3CL-19](https://issues.folio.org/browse/FOLS3CL-19) - Release 2.0.2

FOLS3CL-19 - Release 2.0.2

---

pom.xml

FOLS3CL-20 - Reverting minio sdk version

---

src/main/java/org/folio/s3/client/AwsS3Client.java
src/main/java/org/folio/s3/client/FolioS3Client.java
src/main/java/org/folio/s3/client/MinioS3Client.java
src/test/java/org/folio/s3/client/FolioS3ClientTest.java

FOLS3CL-18 OOM issue

---

NEWS.md
pom.xml
src/main/java/org/folio/s3/client/AwsS3Client.java
src/main/java/org/folio/s3/client/FolioS3Client.java
src/main/java/org/folio/s3/client/MinioS3Client.java
src/test/java/org/folio/s3/client/FolioS3ClientTest.java

FOLS3CL-19 - Release 2.0.3

---

NEWS.md
pom.xml
src/main/java/org/folio/s3/client/MinioS3Client.java
src/main/resources/log4j2-json.properties
src/test/java/org/folio/s3/client/FolioS3ClientTest.java

FOLS3CL-19 - Release 2.0.4

---

pom.xml

[FOLS3CL-23](https://issues.folio.org/browse/FOLS3CL-23) - software.amazon.awssdk:s3 security vulnerabilities
software.amazon.awssdk:s3 security vulnerabilities
software.amazon.awssdk:s3 version upgrade to 2.21.19
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …

FOLS3CL-23 - software.amazon.awssdk:s3 security vulnerabilities

---

NEWS.md
pom.xml

[FOLS3CL-24](https://issues.folio.org/browse/FOLS3CL-24) - folio-s3-client: module release
Release v2.0.6.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

Release 2.0.6

---

src/main/java/org/folio/s3/client/FolioS3Client.java
src/main/java/org/folio/s3/client/MinioS3Client.java
src/test/java/org/folio/s3/client/FolioS3ClientTest.java

In order to implement cleanup job for Profile picture feature , 
we need to fetch 70k records for comparison , in current implementation we cant do it because it returns single list which might cause OOM issue. 
With our change we have added pagination functionality in it.  
Ideally all of the PRs involved in breaking changes would be merged in the same …

[MODUSERS-423]-Added method for pagination

---

NEWS.md
pom.xml

[FOLS3CL-28](https://folio-org.atlassian.net/browse/FOLS3CL-28) - folio-s3-client: module release

Release 2.1.0

---

pom.xml
src/main/java/org/folio/s3/client/AwsS3Client.java
src/test/java/org/folio/s3/client/FolioS3ClientTest.java
src/test/resources/log4j2.properties

[FOLS3CL-31](https://folio-org.atlassian.net/browse/FOLS3CL-31) - AWS S3: writing limitation
S3 SDK large files uploading fails in case os size > 5 Gb
Moving writing logic toTransfer Manager implementation
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …

FOLS3CL-31 - AWS S3: writing limitation

---

NEWS.md
pom.xml

[FOLS3CL-30](https://folio-org.atlassian.net/browse/FOLS3CL-30) - Release 2.1.1

FOLS3CL-30 - Release 2.1.1

---

src/test/java/org/folio/s3/client/FolioS3ClientTest.java

[FOLS3CL-32](https://folio-org.atlassian.net/browse/FOLS3CL-32) - TD: Improve unit tests
Fixing unit tests issues and refactoring .
Adding option: --security-opt seccomp=unconfined to container startup.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …

FOLS3CL-32 - TD: Improve unit tests

---

NEWS.md
pom.xml

[FOLS3CL-34](https://folio-org.atlassian.net/browse/FOLS3CL-34) - Release 2.2.0

FOLS3CL-34 - Release 2.2.0

---

Jenkinsfile
pom.xml

[FOLS3CL-38](https://folio-org.atlassian.net/browse/FOLS3CL-38) - Update to folio-s3-client Java 21
Java version upgrading
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …

FOLS3CL-38 - Update to folio-s3-client Java 21

---

NEWS.md
pom.xml

[FOLS3CL-38](https://folio-org.atlassian.net/browse/FOLS3CL-38) - Release 2.3.0

FOLS3CL-39 - Release 2.3.0
